### ISSUE TITLE
README should be named README.adoc

### ISSUE THREAD

**Issue by vphantom** [fbriere/psx-bios-package#1]
I was wondering why it didn't display as expected... :)  (Unless... wait, you're using AsciiDoc? It's so similar I didn't notice until I looked at your man page!  (For which Markdown has "Ronn" which I thought you were using.))  Thanks for teaching me that GitHub supports AsciiDoc just as well as GitHub Flavored Markdown!

**Comment by fbriere** [comment]
> Unless... wait, you're using AsciiDoc?

Nah, it was just "something human-readable", back when Gitorious was still a thing, and not every README was made to be pushed to GitHub.
